<?php require_once(PARTS_FOLDER . "header.php"); ?>

<div class="content clearfix">
    <div class="col-12">
        <div class="table">
            <h2 class="title">Allgemeine Geschäftsbedingungen</h2>
        </div>
        <h2>der FLIRTBAR Sh.p.k. für die flirtbar.net Dienste (in der Fassung vom 17.11.2005)</h2>
        <p><strong>Geltungsbereich</strong><br>Die Teilnahme an den "flirtbar.net" Diensten liegen den nachstehenden Bedingungen von "flirtbar.net" zu Grunde. Diese Bedingungen sind zurzeit in deutscher Sprache verfügbar. Durch die Anmeldung bei "flirtbar.net" und die Nutzung der angebotenen Dienste erklärt der Teilnehmer, die "flirtbar.net" Dienste in Übereinstimmung mit dem anwendbaren Recht und diesen Geschäftsbedingungen zu nutzen.</p>
        <p><strong>Anmeldebedingungen</strong><br>Bestimmte "flirtbar.net" Dienste können nur nach einer Registrierung als Teilnehmer genutzt werden. Teilnehmer kann jeder werden, der das Anmeldeformular vollständig und wahrheitsgemäß ausfüllt ("Anmeldedaten"). Der Teilnehmer erhält daraufhin ein Pseudonym und ein Passwort ("Nutzerdaten"). Der Teilnehmer ist verpflichtet, die Anmeldedaten auf dem aktuellen Stand zu halten. Die Nutzerdaten sind vom Teilnehmer geheim zu halten. Die Registrierung ist kostenfrei. Jeder Teilnehmer darf nur eine Teilnehmerschaft haben und die damit verbundenen Vorteile in Anspruch nehmen. Die Teilnehmerschaft und die damit verbundenen "flirtbar.net" Dienste dürfen ausschließlich zum persönlichen Gebrauch verwendet werden und sind nicht übertragbar. "flirtbar.net" speichert die Vertragsbedingungen nicht für jeden Teilnehmer individuell. Der Teilnehmer kann diese Geschäftsbedingungen über einen Link im Servicebereich der Website abrufen.</p>
        <p><strong>Verantwortlichkeit für Minderjährige</strong><br>Für kostenlose anmeldepflichtige "flirtbar.net" Dienste dürfen sich Teilnehmer anmelden, soweit sie sich über die Konsequenzen der Einwilligung zur Verarbeitung und Nutzung ihrer Daten bewusst sind, die Bedeutung einer solchen Zustimmung verstehen und die Nutzung eines Dienstes durch Minderjährige nachfolgend nicht ausdrücklich ausgeschlossen ist. Für den Fall, dass Erziehungsberechtigte die Nutzung anmeldepflichtiger "flirtbar.net" Dienste durch Minderjährige zulassen, akzeptieren sie ihre Verantwortlichkeit für das Verhalten des Minderjährigen online, die Zugangskontrolle sowie für die Konsequenzen bei einem Missbrauch der "flirtbar.net" Dienste durch den Minderjährigen. Die Erziehungsberechtigten sind sich darüber bewusst, dass einige Angebote des "flirtbar.net" Netzwerkes Inhalte enthalten können, die zur Nutzung durch Minderjährige nicht geeignet sind.</p>
        <p><strong>Datenschutz</strong><br>a) "flirtbar.net" achtet die Privatsphäre der Nutzer und hält alle anwendbaren Datenschutzbestimmungen strengstens ein. b) Personenbezogene Daten, die "flirtbar.net" im Rahmen der Anmeldung sowie zur Durchführung der "flirtbar.net" Dienste erhebt oder verarbeitet, nutzt "flirtbar.net" nur im Rahmen der gesetzlichen Vorschriften. "flirtbar.net" verwendet die Daten des Teilnehmers ausschließlich zur Durchführung des jeweiligen Dienstes. Darüber hinaus nutzt "flirtbar.net" personenbezogene Daten z.B. für Zwecke der Beratung, Werbung und Marktforschung. c) "flirtbar.net" wird die personenbezogenen Nutzerdaten nicht ohne das ausdrückliche Einverständnis des Teilnehmers an Dritte weiterleiten. Dies gilt nicht, soweit "flirtbar.net" gesetzlich zur Herausgabe von Daten verpflichtet ist.</p>
        <p><strong>Urheberrechtlich geschütztes Material</strong><br>Alles Material innerhalb des "flirtbar.net" Netzwerks, einschließlich aller Texte, Software, HTML-/Java-/Flash-Quellcodes, Fotos, Videos, Grafiken, Musik und Sounds, ist urheberrechtlich geschützt und zwar sowohl als individuelle Leistung als auch als Sammlung. Das Herunterladen und der Gebrauch von urheberrechtlich geschütztem Material, das von "flirtbar.net" oder dritter Seite zur Verfügung gestellt wird, ist Teilnehmern ausschließlich für den Privatgebrauch erlaubt, soweit dies im Rahmen der anwendbaren gesetzlichen Bestimmungen und dieser Geschäftsbedingungen geschieht. Teilnehmer dürfen dieses Material jedoch nicht über diesen Rahmen hinaus vervielfältigen, nachbilden, übertragen, vertreiben, veröffentlichen, kommerziell verwerten, auf andere Weise in elektronischer oder anderer Form in ein anderes Datenformat übertragen oder in sonstiger Weise nutzen.</p>
        <p><strong>Gewährleistungsausschluß / Haftungsbeschränkungen</strong><br>Die Nutzung der "flirtbar.net" Dienste erfolgt auf eigenes Risiko der Nutzer. "flirtbar.net" übernimmt keine Haftung dafür, dass die "flirtbar.net" Dienste zu jeder Zeit ohne Unterbrechung, zeitgerecht, sicher und fehlerfrei zur Verfügung stehen. "flirtbar.net" übernimmt keine Haftung für verloren gegangene Informationen und Daten des Teilnehmers. Informationen und Ratschläge, die ein Nutzer im Rahmen der "flirtbar.net" Dienste erhält, sei es auf Webseiten, per E-Mail oder Telefax, schriftlich oder mündlich, begründen keinerlei Gewährleistung von "flirtbar.net", sofern dies nicht ausdrücklich vereinbart wurde.</p>
        <p><strong>Änderungen der Dienste</strong><br>"flirtbar.net" kann nach freiem Ermessen festlegen, welche Dienste in welchem Umfang zur Verfügung gestellt werden. Einschränkungen, Erweiterungen und andere Änderungen dieser Dienste durch "flirtbar.net" sind jederzeit zulässig und unterliegen ebenfalls den folgenden Teilnahmebedingungen.</p>
        <p><strong>Kündigung der Teilnehmerschaft</strong><br>a) "flirtbar.net" ist berechtigt, den Vertrag über die Teilnahme an den "flirtbar.net" -Diensten mit dem Teilnehmer jederzeit mit einer Frist von einem Monat per E-Mail zu kündigen. Ferner ist "flirtbar.net" zur fristlosen Kündigung aus wichtigem Grund ohne vorherige Abmahnung berechtigt. Ein wichtiger Grund liegt insbesondere vor, wenn der Teilnehmer gegen anwendbares Recht oder gegen diese allgemeinen Geschäftsbedingungen verstößt. b) Der Teilnehmer kann die Teilnehmerschaft jederzeit gegenüber "flirtbar.net" kündigen. Wenn der Teilnehmer sein Account löscht, werden alle Daten aus der Datenbank gelöscht. Ein wiederherstellen des Accounts ist dann nicht mehr möglich. c) Mit Wirksamkeit der Kündigung hat "flirtbar.net" das Recht, jegliche Daten, die der Teilnehmer in das "flirtbar.net" Netzwerk eingestellt oder zugesandt bekommen hat, zu löschen. d) Noch vorhandene Kronkorken zum Zeitpunkt des löschens verfallen und können nicht ausbezahlt werden.</p>
        <p><strong>Kostenlose Community-Dienste</strong><br>Dem Teilnehmer obliegen hinsichtlich des Mail-Dienstes insbesondere folgende Pflichten: a) die Mail-Adresse weder zum Abruf noch zur Verbreitung von sitten- oder rechtswidrigen Informationen zu benutzen; b) die geltenden Jugendschutzvorschriften zu beachten; c) die Privatsphäre anderer zu respektieren und daher in keinem Fall belästigende, verleumderische oder bedrohende Inhalte per E-Mail zu verschicken oder per sms; d) keine Anwendungen auszuführen, die zu einer Veränderung der physikalischen oder logischen Struktur der genutzten Netze führen können. Die Nutzung des Mail-Postfaches für den Versand von Massen-Mails/ Massen SMS (Spamming), mail-bombing und jede andere Form von Werbe- oder Marketingbotschaften ist nicht gestattet und verpflichtet den Teilnehmer zum Ersatz des entstandenen Schadens. Die vorhergehenden Vorschriften über den Mail-Dienst gelten in vollem Umfange auch für E-Mail-Dienste auf SMS-Basis.</p>
        <p><strong>Umfragen, Chatrooms, Konferenzen, Kontaktanzeigen</strong><br>Funktionierende Kommunikation unter den Teilnehmern und eine optimale Nutzung der "flirtbar.net" Dienste durch den Einzelnen setzen voraus, dass die Teilnehmer respektvoll miteinander umgehen und gewisse Verhaltensregeln einhalten. Dazu gehört, dass die Teilnehmer sich weder in Mails noch in Beiträgen zu "flirtbar.net" Umfragen, in Chatrooms, Konferenzen oder Kontaktanzeigen ("Teilnehmerseiten"), verletzend, verleumderisch, beleidigend, bedrohend, obszön, rassistisch oder anderweitig gesetzes- oder sittenwidrig äußern. Die Teilnehmer verpflichten sich, auf die kulturellen und religiösen Belange und die Meinungen anderer Teilnehmer Rücksicht zu nehmen. Die "flirtbar.net" Teilnehmerseiten sollen Privatpersonen ein Forum zur Meinungsäußerung, Meinungsbildung und zum gegenseitigen Kennenlernen zur Verfügung stellen. Daher ist den Teilnehmern Reklame oder eine andere Form kommerzieller Werbung, insbesondere auch für andere Webseiten auf den "flirtbar.net" Teilnehmererseiten, nicht erlaubt. "flirtbar.net" behält sich das Recht vor, Beiträge oder Teile davon, die nicht den oben genannten Regeln entsprechen, zu löschen und den Zugriff auf die "flirtbar.net" Teilnehmerseite ganz zu sperren. "flirtbar.net" weist darauf hin, dass Identitäten, Aussagen und Informationen von Personen, die sich im Internet bewegen, falsch sein können und "flirtbar.net" keinerlei Gewähr für das Verhalten Dritter übernimmt, unabhängig davon, wo es stattfindet "flirtbar.net" haftet insbesondere nicht für den Umgang Dritter mit Daten und Informationen, die ein Teilnehmer im Rahmen eines "flirtbar.net" Dienstes anderen Teilnehmer oder Dritten zugänglich macht. Jeder Teilnehmer ist verpflichtet, E-Mails und andere Nachrichten, Namen, Telefon- und Faxnummern, Wohn-, Geschäfts- und E-Mailadressen und URLs, die im Rahmen der Kontaktanzeigen ausgetauscht werden, vertraulich zu behandeln. Solche Information dürfen Dritten nur mit ausdrücklicher Zustimmung des Urhebers oder Inhabers zugänglich gemacht werden. Der Nutzer der Kontaktanzeigen willigt ein, dass Daten von "flirtbar.net" verarbeitet und weitergegeben werden dürfen, soweit dies zur Durchführung des Dienstes in der beschriebenen Art notwendig ist.</p>
        <p>Es ist strengstens verboten, öffentlich seine persönlichen Daten bekannt zu geben. Dazu zählen Telefonnummern, E-Mail Adressen, Skype, MSN, ICQ, Web Links und sonstige Kontaktdaten. Da es genug Suchroboter gibt, welche unsere Seiten nach solchen öffentlichen Daten scannen, wollen wir dies im Vorfeld schon vermeiden. Denn Person bezogene Daten gehören nicht öffentlich auf die Webseite. Wer dagegen verstößt, wird mit sofortiger Wirkung gesperrt.</p>
        <p>Es ist pro Haushalt nur 1 Account bei uns auf der Seite gestattet. Sollten mehrere Accounts (Multiaccounts) von ein und derselben Person (Haushalt) bei uns auf der Seite zu finden sein, werden alle Accounts gesperrt.</p>
        <p>Die FLIRTBAR Sh.p.k. haftet nicht für den Inhalt von SMS oder anderer Nachrichten, die im System versandt und verarbeitet werden. Für den Inhalt ist der jeweilige Absender oder Autor verantwortlich.</p>
        <p>In diesem Chat setzt die FLIRTBAR Sh.p.k. Controller/innen ein, die unter mehreren Identitäten Dialoge führen können. Im System sind diese nicht besonders gekennzeichnet.</p>
        <p>Für Störungen im Telefonnetz oder Internet ist der Seitenbetreiber nicht verantwortlich und nicht haftbar zu machen.</p>
        <p>Der Teilnehmer erkennt an, daß alle Daten gespeichert werden, soweit sie zur Teilnahme am Chat und zur Abrechnung erforderlich sind.</p>
        <p><strong>Salvatorische Klausel</strong>Sollte(n) eine oder mehrere Bestimmungen dieser AGB ungültig sein, so bleibt die Wirksamkeit der übrigen Bestimmungen unberührt</p>
    </div>
</div>

<?php require_once(PARTS_FOLDER . "footer.php"); ?>
